package hibernate.entity;
// Generated 21 d�c. 2017 09:38:56 by Hibernate Tools 5.1.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ordertype generated by hbm2java
 */
@Entity
@Table(name = "ordertype", schema = "public")
public class Ordertype implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private String type;
	private Set<Orderhistorybot> orderhistorybots = new HashSet<Orderhistorybot>(0);

	public Ordertype() {
	}

	public Ordertype(int id, String type) {
		this.id = id;
		this.type = type;
	}

	public Ordertype(int id, String type, Set<Orderhistorybot> orderhistorybots) {
		this.id = id;
		this.type = type;
		this.orderhistorybots = orderhistorybots;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "type", nullable = false, length = 25)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ordertype")
	public Set<Orderhistorybot> getOrderhistorybots() {
		return this.orderhistorybots;
	}

	public void setOrderhistorybots(Set<Orderhistorybot> orderhistorybots) {
		this.orderhistorybots = orderhistorybots;
	}

}
